name: Build and Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t fastapi-app .

      - name: Decode SSH key and save
        run: |
          echo "${{ secrets.EC2_SSH_KEY_B64 }}" | base64 -d > private_key.pem
          chmod 600 private_key.pem

      - name: Install bzip2 on remote server
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            sudo apt-get update -qq && sudo apt-get install -y bzip2 docker.io
          '

      - name: Transfer Docker image
        run: |
          docker save fastapi-app | gzip | ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            gunzip | sudo docker load
          '

      - name: Deploy container
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo docker stop fastapi-app || true
            sudo docker rm fastapi-app || true
            sudo docker run -d --name fastapi-app -p 8080:80 fastapi-app
          EOF
